baseURL = "https://chengyujang.github.io/"
title = 'Phoenix'
locale = 'zh-CN'
theme = "reimu"

defaultContentLanguage = 'zh-cn'
# true：访问 / 会跳转到 /zh-cn/
# false：访问 / 直接就是中文，英文在 /en/
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh-cn]
    label = '简体中文'
    contentDir = 'content/zh-CN'   # 如果你实际目录是 content/zh-CN，就写 content/zh-CN
    weight = 1
    hasCJKLanguage = true

  [languages.en]
    label = 'English'
    contentDir = 'content/en'
    weight = 2

[markup.highlight]
guessSyntax = true
noClasses = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.158.0"